### ISSUE TITLE
How to make sure the generated test files are compilable?

### ISSUE THREAD

**Issue by Outliers1106** [Codium-ai/cover-agent#120]
For example, if there are missed imports or incorrectly initialized variables in Java, the test file can not be compiled. How do you avoid this and make sure to get compilable test cases?

**Comment by EmbeddedDevops1** [comment]
@Outliers1106 That's why we require the `--test-command` option. This will:
1. Compile the tests
2. Run the tests
3. Generate a coverage report

We do this with two [templated Java projects](https://github.com/Codium-ai/cover-agent/tree/main/templated_tests) in our [nightly regression testing](https://github.com/Codium-ai/cover-agent/blob/main/tests_integration/test_all.sh#L76-L94).

Hope that answers your question. I'm going to close the issue but feel free to re-open it if you need further clarification.
